export { default as Navbar } from './navbar'
export { default as Footer } from './footer'
export { default as SkillCard } from './skill-card'
export { default as EducationCard } from './education-card'
export { default as CertificateCard } from './certificate-card'
